name: Create release WC PR
on: 
  workflow_dispatch:
    inputs: 
      release_version:
        description: Release version (major | minor | patch | premajor | preminor | prepatch | prerelease)
        default: patch
        required: true

permissions:
  contents: write # for checkout and commit
  pull-requests: write  # for create pr

jobs:
  createReleasePR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - name: Version up
        run: |
          npx lerna version ${{ github.event.inputs.release_version }} --force-publish=* --no-git-tag-version --no-push --yes --exact
          npm install --package-lock-only
      - name: Get Release Version
        run: |
          RELEASE_VERSION=$(node -p 'require("./lerna.json").version')
          echo "RELEASE_VERSION=${RELEASE_VERSION}" >> $GITHUB_ENV               
      - name: Update .release_wc.txt file
        run: node ./scripts/update-release-wc-file ${{ github.event.sender.login }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          commit-message: 'chore(release-wc): v${{ env.RELEASE_VERSION }}'
          delete-branch: true
          branch: release-pr/release-wc-${{ env.RELEASE_VERSION }}
          branch-suffix: timestamp
          title: Release Request WC v${{ env.RELEASE_VERSION }}
          labels: Release PR
