name: Release Tippy.js' theme
on:
  push:
    branches:
      - master
    paths:
      - 'themes/tippy.js/**'

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 16
          registry-url: https://check.npmjs.org/
      - name: Install dependencies
        run: npm ci
      - name: Build tippy theme
        run: npm run build:tippy-theme

      # Publish
      - name: Publish package
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.FINASTRA_BOT_NPM_AUTH_TOKEN }}
          package: ./themes/tippy.js/package.json
          access: public
