name: Release WC Canary
on:
 pull_request:
    branches:
      - master
    paths:
      - 'packages/**'
      - '!packages/**/package.json'

permissions:
  contents: write # for checkout and commit
  pull-requests: write  # for create pr

jobs:
  createReleasePR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - name: Create canary release
        run: |
          npx lerna version preminor --force-publish=* --no-git-tag-version --no-push --preid canary.$(git rev-parse --short HEAD) --yes --exact
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "chore: Publish"
      - name: Publish to NPM registry with canary tag
        run: npx lerna publish from-package --yes --dist-tag canary
        env:
          NODE_AUTH_TOKEN: ${{secrets.FFDC_BOT_NPM_AUTH_TOKEN}}
