name: Publish Storybook
on:
  push:
    branches:
      - master
    paths:
      - 'libs/**'
      - 'themes/fds-theme/**'
      - '!libs/**/package.json'
      - '!themes/fds-theme/package.json'

permissions:
  contents: write # for checkout and commit
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: master
      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: 15
          registry-url: https://registry.npmjs.org/
      - name: Build Storybook
        run: |
          npm ci
          npm run wc:build:storybook
      - name: Deploy Storybook 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: storybook
          folder: storybook-static
