name: Web Components PR
on:
  pull_request:
    path:
      - 'libs/web-components/**'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Cache Node.js modules
        uses: actions/cache@v1
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-node-
            ${{ runner.OS }}-

      # Setup
      - name: Install Dependencies
        run: npm ci --loglevel=error
        env:
          SKIP_POST_INSTALL: true
      - name: Build DevKit
        run: npm run build:devkit
      - name: Build web components
        run: npm run wc:build

      # Compliance Check
      - name: Compliance Check
        run: npm run wc:compliance:check

      # Test
      - name: Unit tests
        run: npm run wc:test
      - name: Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: ./wc-coverage/lcov.info
          fail_ci_if_error: true
          verbose: true

      # Storybook
      - name: Build Storybook
        run: npm run wc:build:storybook
      - name: Deploy storybook to Netlify
        uses: nwtgck/actions-netlify@v1.1
        with:
          publish-dir: './storybook-static'
          production-branch: master
          github-token: ${{ secrets.GITHUB_TOKEN }}
          deploy-message: 'Deploy Storybook from GitHub Actions'
          enable-pull-request-comment: false
          enable-commit-comment: true
          overwrites-pull-request-comment: true
          alias: deploy-preview-${{ github.event.number }}
          github-deployment-environment: storybook-pr
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        timeout-minutes: 1
